### PR TITLE
fix: revive dead FormData Content-Type warning (#6067)

### LINKED ISSUE #6067: Custom content-type header with FormData body warning is dead code
We have code which tries to warn the user when they create an HTTP message with a FormData body and a custom Content-Type header: https://github.com/cloudflare/workerd/blob/ee6d283b7e6e6a90c42567b68f07bb077ea0857e/src/workerd/api/http.c%2B%2B#L180-L184

The warning is logged when this if condition is true: https://github.com/cloudflare/workerd/blob/ee6d283b7e6e6a90c42567b68f07bb077ea0857e/src/workerd/api/http.c%2B%2B#L177

The condition is guaranteed never to be true, because:

- `MimeType::FORM_DATA` is a `ConstMimeType` (with content: `multipart/form-data`)
- `ct` is a `kj::String` (with content: `multipart/form-data; boundary=...`)
- `ConstMimeType::operator==(kj::StringPtr)` does not parse the string, but instead splits at the first `/` and compares everything before, then everything after: https://github.com/cloudflare/workerd/blob/ee6d283b7e6e6a90c42567b68f07bb077ea0857e/src/workerd/util/mimetype.h#L38
- `"form-data" != "form-data; boundary=..."`, so the if condition is always false

I would say there are two bugs here:

1. `ExtractedBody::contentType` should preferably strongly typed, not just a `kj::String`
2. `ConstMimeType::operator==(kj::StringPtr)` is a footgun, and should probably not exist -- comparing string MIME types should involve parsing them

### PR DESCRIPTION
**Pull request by harrishancock**
The `logWarning()` in `Body::Body` that warns when a `FormData` body is paired with a custom Content-Type header was dead code. The comparison used `ConstMimeType::operator==(kj::StringPtr)`, which compared the full substring after '/' against the subtype — so 'form-data; boundary=...' never matched 'form-data'.

Fix the comparison by parsing the content-type string into a `MimeType` first, then comparing against `MimeType::FORM_DATA`. The `MimeType` equality operator correctly ignores MIME parameters like boundary.

Also remove `ConstMimeType::operator==(kj::StringPtr)` entirely — it was a footgun with only this one (buggy) caller, and any future use would hit the same parameter-ignoring trap.

Add a streaming tail worker test that verifies the warning is emitted and captured in the tracing system when a Request is constructed with a `FormData` body and a custom Content-Type header.

Fixes #6067

### CODE REVIEW

File: src/workerd/api/streams/internal.c++ [hunk 1]
```diff
@@ -23,6 +23,9 @@ namespace {
 // papers over is fixed.
 [[noreturn]] void throwTypeErrorAndConsoleWarn(kj::StringPtr message) {
   KJ_IF_SOME(context, IoContext::tryCurrent()) {
+    // TODO(cleanup): This guard predates streaming tail workers. logWarning() already emits to
+    // the tracer when one exists, so this check suppresses the warning for tail-worker-only
+    // users. Consider replacing with a check that also accounts for getWorkerTracer().
```
Comment (harrishancock) [inline src/workerd/api/streams/internal.c++]: When I want crawling around looking for other warnings to add to the new test, I discovered that most are guarded by `isInspectorEnabled()`.

IIRC, this guard only exists because we originally didn't have anywhere for the warnings to go when there was no inspector enabled, so we skipped the (obviously negligible) overhead of constructing the warning message in that case.

Shall we delete these guards, now that tail workers should see the warnings?

Comment (jasnell) [reply src/workerd/api/streams/internal.c++]: sounds reasonable to me

File: src/workerd/api/tests/warnings-tail.js [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+let allEvents = [];
+
+export default {
+  tailStream(event) {
+    allEvents.push(event.event);
+    return (event) => {
+      allEvents.push(event.event);
+    };
+  },
+};
```
Comment (jasnell) [inline src/workerd/api/tests/warnings-tail.js:33]: Side note... love that we can use this now to test logging side effects.

File: src/workerd/api/http.c++ [hunk 3]
```diff
@@ -174,14 +174,16 @@ Body::Body(jsg::Lock& js, kj::Maybe<ExtractedBody> init, Headers& headers)
...
             headers.setCommon(capnp::CommonHeaderName::CONTENT_TYPE, kj::mv(ct));
-          } else if (MimeType::FORM_DATA == ct) {
-            // Custom content-type request/responses with FormData are broken since they require a
-            // boundary parameter only the FormData serializer can provide. Let's warn if a dev does this.
-            IoContext::current().logWarning(
-                "A FormData body was provided with a custom Content-Type header when constructing "
-                "a Request or Response object. This will prevent the recipient of the Request or "
-                "Response from being able to parse the body. Consider omitting the custom "
-                "Content-Type header.");
+          } else KJ_IF_SOME(parsed, MimeType::tryParse(ct)) {
```
Comment (jasnell) [inline src/workerd/api/http.c++:177]: Ah, yeah I remember now... I had intentially matched the semantics of the previous check (before `MimeType` was introduced) which didn't attempt to do any parsing. I'd meant to come back to revisit it but I see I forgot to add a `TODO` (not that we typically pay much attention to TODOs in general).

File: src/workerd/api/http.c++ [hunk 4]
```diff
@@ -1058,6 +1063,9 @@ jsg::Ref<Response> Response::constructor(jsg::Lock& js,
           "Response with null body status (101, 204, 205, or 304) cannot have a body.");
 
       auto& context = IoContext::current();
+      // TODO(cleanup): This guard predates streaming tail workers. logWarning() already emits to
+      // the tracer when one exists, so this check suppresses the warning for tail-worker-only
+      // users. Consider replacing with a check that also accounts for getWorkerTracer().
```
Comment (jasnell) [inline src/workerd/api/http.c++]: We could probably generalize the check in a utility that returns true if either inspector is enabled or tail stream tail workers are active.

**Review by jasnell — APPROVED** [review]

File: src/workerd/api/http.c++ (hunk 4 above)
Comment (harrishancock) [reply src/workerd/api/http.c++]: Force-pushed a change which adds an `IoContext::hasWarningHandler()` to replace these checks.

File: src/workerd/api/tests/warnings-tail.js [hunk 5]
```diff
@@ -0,0 +1,68 @@
...
+// ================================================================================================
+// Expected warnings registry.
+//
+// Add new entries here when introducing logWarning() calls. Each entry is a substring that must
+// appear in at least one warn-level tail event's message. The trigger worker (warnings-test.js)
+// must exercise a code path that produces each warning.
+//
+// NOTE: Some logWarning() calls go through jsg::Lock::logWarning() instead of
+// IoContext::logWarning(). The jsg path does not currently emit to the tracer, so those warnings
+// are not observable via tail workers and cannot be tested here (e.g. .text() on non-text body).
```
Comment (harrishancock) [inline src/workerd/api/tests/warnings-tail.js:15]: This was another unwelcome discovery. I _suspect_ that `jsg::Lock::logWarning()`'s behavior is buggy, and that we actually want warnings logged that way to go to tail workers.

Relatedly, errors reported via `jsg::Lock::reportError()` are intended to go to tail workers ... but only when the inspector attached: https://github.com/cloudflare/workerd/blob/37dc327ecf58166645c6849f0961828a024fede8/src/workerd/io/worker.c%2B%2B#L1126-L1137

I'll leave this to a future PR.
