### PR TITLE
Strip Authorization header on cross-origin redirects

### LINKED ISSUE #2223: 🐛 Bug Report — Strange header issue with `fetch` URLs that redirect
> [!WARNING]  
> WIP issue please be patient

I have a worker where I am attempting to fetch artifacts from the [github api](https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#get-an-artifact).

This API returns a 302 to a signed download URL. So what I think is happening is the `Authentication` header is also being sent to the signed url server which results in an error.

Repro that I'm working on:
https://github.com/Hacksore/fetch-with-github-artifacts

Same issue exists in prod:
https://fetch-with-github-artifacts.hacksore.workers.dev

I was able to figure out that it has to be the auth token making it down stream.

```
curl -vvv -H "Authorization: Bearer ligma" https://productionresultssa16.blob.core.windows.net
```

## Note workaround:
We just have to fetch without redirect and then do another fetch to omit sending the `Authenticated` header.

### PR DESCRIPTION
**Pull request by npaun**
Fixes #2223

### CODE REVIEW

**Comment by danlapid** [comment]
@kentonv

File: src/workerd/api/http.c++ [hunk 1]
```diff
@@ -1595,6 +1595,23 @@ jsg::Promise<jsg::Ref<Response>> handleHttpRedirectResponse(jsg::Lock& js,
...
+    if (KJ_ASSERT_NONNULL(currentUrl).getOrigin() != KJ_ASSERT_NONNULL(locationUrl).getOrigin()) {
+          // If request’s current URL’s origin is not same origin with locationURL’s origin, then
+          // for each headerName of CORS non-wildcard request-header name, delete headerName from
+          // request’s header list.
+          // -- Fetch spec s. 4.4.13
+          // <https://fetch.spec.whatwg.org/#http-redirect-fetch>
+          //  (NB: "CORS non-wildcard request-header name" consists solely of "Authorization")
+
+          jsRequest->getHeaders(js)->delete_(jsg::ByteString(kj::str("authorization")));
+    }
```
Comment (jasnell) [inline src/workerd/api/http.c++]:
```suggestion
    if (KJ_ASSERT_NONNULL(currentUrl).getOrigin() != KJ_ASSERT_NONNULL(locationUrl).getOrigin()) {
      // If request’s current URL’s origin is not same origin with locationURL’s origin, then
      // for each headerName of CORS non-wildcard request-header name, delete headerName from
      // request’s header list.
      // -- Fetch spec s. 4.4.13
      // <https://fetch.spec.whatwg.org/#http-redirect-fetch>
      //  (NB: "CORS non-wildcard request-header name" consists solely of "Authorization")

      jsRequest->getHeaders(js)->delete_(jsg::ByteString(kj::str("authorization")));
    }
```

Comment (npaun) [reply src/workerd/api/http.c++]: Is this just about indenting? This is what clang-format gave me.

Comment (npaun) [reply src/workerd/api/http.c++]: Although it allowed me to fix it... I am so confused now.

File: src/workerd/api/http.c++ [hunk 2]
```diff
@@ -1595,6 +1595,23 @@ jsg::Promise<jsg::Ref<Response>> handleHttpRedirectResponse(jsg::Lock& js,
     return js.rejectedPromise<jsg::Ref<Response>>(kj::mv(exception));
   }
 
+
+  if (FeatureFlags::get(js).getStripAuthorizationOnCrossOriginRedirect()) {
+    auto base = urlList.back().toString();
+    auto currentUrl = jsg::Url::tryParse(base.asPtr());
+    auto locationUrl = jsg::Url::tryParse(location, base.asPtr());
+    if (KJ_ASSERT_NONNULL(currentUrl).getOrigin() != KJ_ASSERT_NONNULL(locationUrl).getOrigin()) {
```
Comment (jasnell) [inline src/workerd/api/http.c++]: It is entirely possible for either one of these to fail, in which case the `KJ_ASSERT_NONNULL` calls below would result in an `internal error` being thrown. We should check to see what browsers do when the URL returned by the location header is invalid and cannot be parsed. Does it just ignore it? Does it go ahead and remove the `authorization` header? etc.

If it matches the behavior in browsers, then what I would suggest here is that if either of these fail parsing, we just go ahead and remove the `authorization` header and do not throw any errors.

File: src/workerd/io/compatibility-date.capnp [hunk 3]
```diff
@@ -990,4 +990,12 @@ struct CompatibilityFlags @0x8f8c1b68151b6cef {
...
   # This flag is experimental and may be removed in the future. It is added for
   # testing purposes.
+
+  stripAuthorizationOnCrossOriginRedirect @114 :Bool
+      $compatEnableFlag("strip_authorization_on_cross_origin_redirect")
+      $compatDisableFlag("retain_authorization_on_cross_origin_redirect")
+      $compatEnableDate("2025-09-01");
+  # This flag ensures the Authorization header is not passed on if a request is redirected to a URL
+  # with a different origin than the requested URL. This behavior is required by the WHATWG fetch
+  # specification. For security reasons, this flag should not be disabled.
```
Comment (kentonv) [inline src/workerd/io/compatibility-date.capnp]: I actually disagree with this. It is usually not a security risk to disable this flag, and in fact may be desirable. In fact I think it was a mistake for the spec to add this requirement -- but since they added it, we have to follow it.

I would change the comment to something like:

> The current version of the Fetch API spec requires that, when automatic redirects are enabled, and a redirect points to a URL at a different origin, if the original request contained an `Authorization` header, that header must be removed before following the redirect. This requirement was added to the Fetch spec in 2022, well after Cloudflare Workers originally implemented it. Hence, Workers did not originally implement this requirement. This requirement is backwards-incompatible, and so the new behavior is guarded by a compatibility flag. Note that the old behavior was not inherently insecure, and indeed could be desirable in many circumstances. For example, if an API that requires authorization wishes to change its hostname, it might wish to redirect to the new hostname while having the client send along their credentials. Under the new fetch behavior, such a redirect will break clients, and this has legitimately broken real use cases. However, it's true that the old behavior could be a "gotcha" leading to security problems when combined with other mistakes. Hence, the spec was changed, and Workers must follow the spec.

File: src/workerd/api/http.c++ (hunk 1 above)
Comment (jasnell) [reply src/workerd/api/http.c++]: yeah, just indenting. clang-format makes me sad sometimes

File: src/workerd/io/compatibility-date.capnp (hunk 3 above)
Comment (jasnell) [reply src/workerd/io/compatibility-date.capnp]: We might also set a new record for most number of new compat flags added in a single week lol

File: src/workerd/api/http.c++ (hunk 2 above)
Comment (npaun) [reply src/workerd/api/http.c++]: What kind of invalid URL are you thinking of... it's hard to find something Chrome won't take.

File: src/workerd/io/compatibility-date.capnp (hunk 3 above)
Comment (npaun) [reply src/workerd/io/compatibility-date.capnp]: I had to fix merge conflicts twice within a couple minutes, so I think that might be accurate.

File: src/workerd/api/http.c++ (hunk 2 above)
Comment (npaun) [reply src/workerd/api/http.c++]: Screenshot 2025-08-13 at 4 00 45 PM


Like what is this supposed to do?

Comment (jasnell) [reply src/workerd/api/http.c++]: Try this one... I know chrome doesn't like it: `'ÿ: not a valid url'`

Comment (jasnell) [reply src/workerd/api/http.c++]: the address line will always try to be as resilient as possible. Just throw garbage into the `Location` head and see what happens.

Comment (npaun) [reply src/workerd/api/http.c++]: We discussed in chat - browsers throw an error for this so we will too.

File: src/workerd/api/http.c++ [hunk 4]
```diff
@@ -1595,6 +1595,38 @@ jsg::Promise<jsg::Ref<Response>> handleHttpRedirectResponse(jsg::Lock& js,
...
+
+    auto locationUrl = jsg::Url::tryParse(location, base.asPtr());
+
+    if (locationUrl == kj::none) {
+      auto exception =
+        JSG_KJ_EXCEPTION(FAILED, TypeError, "Invalid Location header; unable to follow redirect.");
+      return js.rejectedPromise<jsg::Ref<Response>>(kj::mv(exception));
+    }
+
+    if (KJ_ASSERT_NONNULL(currentUrl).getOrigin() != KJ_ASSERT_NONNULL(locationUrl).getOrigin()) {
```
Comment (kentonv) [inline src/workerd/api/http.c++]: The KJ_ASSERT_NONNULLs here are redundant since the code above ensures that these cannot possibly be null. This makes the code hard to read: It _looks like_ we're doing checks here that could fail and throw exceptions, and one has to carefully read the code that comes before it to see that's not the case.

You can avoid this problem by changing the checks above to use KJ_UNWRAP_OR, like:

```cpp
    auto currentUrl = KJ_UNWRAP_OR(jsg::Url::tryParse(base.asPtr()), {
      auto exception =
        JSG_KJ_EXCEPTION(FAILED, TypeError, "Invalid current URL; unable to follow redirect.");
      return js.rejectedPromise<jsg::Ref<Response>>(kj::mv(exception));
    });
```

Now you can use `currentUrl` without having to check it for nullness.

**Review by kentonv — APPROVED** [review]

File: src/workerd/api/http.c++ (hunk 4 above)
Comment (npaun) [reply src/workerd/api/http.c++]: cool macro - thanks!

**Comment by ConradIrwin** [comment]
@npaun Is this supposed to be fixed on the latest wrangler (v4.45.3)?

I have a test repo at https://github.com/ConradIrwin/fetch-example (very similar to the original bug in #2223) which shows that it is still sending the authorization header on cross-origin redirect.

**Comment by npaun** [comment]
Hi @ConradIrwin, the compatibility date in your example, `2024-01-01`, is too old. It needs to be set to at least [`2025-09-01`](https://github.com/cloudflare/workerd/blob/b0a7b2f67d9c27849657d5d8c94f9a983d9dd727/src/workerd/io/compatibility-date.capnp#L991C26-L991C36), for the fix to be enabled. I'd recommend updating the compatibility date so you get all our latest features and fixes.

 If it's not possible to change the compatibility date, you can enable the feature flag `strip_authorization_on_cross_origin_redirect` on its own to get the new behaviour.

**Comment by ConradIrwin** [comment]
Thank you and sorry for the noise!

**Comment by ConradIrwin** [comment]
I think this flag may be missing here: https://developers.cloudflare.com/workers/configuration/compatibility-flags/

**Comment by npaun** [comment]
> I think this flag may be missing here: [developers.cloudflare.com/workers/configuration/compatibility-flags](https://developers.cloudflare.com/workers/configuration/compatibility-flags/)

Indeed. Thanks for spotting this - I'll get that fixed up.
