### PR TITLE
Reset uncaught exception handling after startup execution

### LINKED ISSUE #5332: Make SetCaptureStackTraceForUncaughtExceptions configurable for a 26% speed boost
This line will always execute in workerd (because `errorReporter != kj::none`)

https://github.com/cloudflare/workerd/blob/65feef11818ad26e4e7a2b6fe3a640b3f76416bb/src/workerd/io/worker.c%2B%2B#L1309-L1311

This has an effect even when running normally *without* an inspector attached, and even when the thrown objects *are* caught (So the "ForUncaughtExceptions" bit is apparently not true – will investigate this in the v8 codebase)

For certain Next.js streaming rendering workloads this can have quite an impact because React uses `throw` for flow control (I know, let's not go there).

By removing this line I see a 26% improvement in performance – again, just when running normally, no inspector attached.

If we want to keep the logic as is (Do we? Or should we drop the `errorReporter != kj::none` bit?) – then I propose that we make it configurable, so that people running workerd in production, or when benchmarking, are not hindered by this behaviour. Basically I just want a way to not have this line execute.

### PR DESCRIPTION
**Pull request by mhart**
Fixes #5332

I've confirmed this keeps the stack for any uncaught errors during startup:

```
service main: Uncaught Error: wtf
  at worker.js:14:11 in recurse2
  at worker.js:9:3 in recurse1
  at worker.js:16:3 in recurse2
  at worker.js:9:3 in recurse1
  at worker.js:16:3 in recurse2
  at worker.js:9:3 in recurse1
  at worker.js:16:3 in recurse2
  at worker.js:9:3 in recurse1
  at worker.js:16:3 in recurse2
  at worker.js:9:3 in recurse1
```

Turning this off any earlier (eg at the end of the Script constructor) is too early:

```
service main: Uncaught Error: wtf
  at worker.js:14:10
```

I've also confirmed this improves performance of running scripts with `throw` patterns as per #5332

### CODE REVIEW

File: src/workerd/io/worker.c++ [hunk 1]
```diff
@@ -1832,6 +1832,12 @@ Worker::Worker(kj::Own<const Script> scriptParam,
               impl->permanentException);
         }
       });
+
+      // Reset this back to its default after startup execution
+      // Leaving it on comes at the expense of collecting stack traces for all thrown exceptions
+      if (script->isolate->impl->inspector == kj::none) {
```
Comment (anonrig) [inline src/workerd/io/worker.c++:1931]: Should we set it to false regardless of inspector? Since we use inspector for profiling as well?

File: src/workerd/io/worker.c++ [hunk 2]
```diff
@@ -1832,6 +1832,12 @@ Worker::Worker(kj::Own<const Script> scriptParam,
               impl->permanentException);
         }
       });
+
+      // Reset this back to its default after startup execution
+      // Leaving it on comes at the expense of collecting stack traces for all thrown exceptions
```
Comment (anonrig) [inline src/workerd/io/worker.c++:1929]: Would you mind adding a link to the github issue, so we don't lose the context?

File: src/workerd/io/worker.c++ (hunk 1 above)
Comment (kentonv) [reply src/workerd/io/worker.c++:1931]: EDIT: Ignore comment, I misread the condition.

In the `Script` constructor, we do:

```cpp
      if (isolate->impl->inspector != kj::none || errorReporter != kj::none) {
        lock.v8Isolate->SetCaptureStackTraceForUncaughtExceptions(true);
      }
```

So if the inspector is off, but `errorReporter` is used (which is always the case in workerd, and in dynamic isolates), then the code as currently written will leave `SetCaptureStackTraceForUncaughtExceptions()` on.

I think that's not what we want? Seems like we should just turn it off unconditionally here.

Comment (kentonv) [reply src/workerd/io/worker.c++:1931]: Oops, I misread the conditional.

OK, I could go either way on this.

File: src/workerd/io/worker.c++ (hunk 2 above)
Comment (mhart) [reply src/workerd/io/worker.c++:1929]: Yeah, good idea 👍

File: src/workerd/io/worker.c++ (hunk 1 above)
Comment (mhart) [reply src/workerd/io/worker.c++:1931]: I'll check what the behaviour's actually like in the inspector after this change (we'd still want *some* way of getting unhandled exceptions with the inspector on if the user wants to – just not sure if there's a way to manually turn it on via Protocol Monitor or similar)

**Comment by kentonv** [comment]
@mhart was there something more you wanted to check before this lands or should I merge it?

**Comment by mhart** [comment]
> @mhart was there something more you wanted to check before this lands or should I merge it?

Ah yeah good point, this slipped off my radar, will look again today

**Comment by kentonv** [comment]
@mhart ping

**Comment by mhart** [comment]
Have played around with this a bunch now including with debug profiler sessions, as well as via `wrangler dev`+`MINIFLARE_WORKERD_PATH=`.

I can't observe any difference in behaviour in terms of error handling at the global level, or within a fetch handler, aside from the fact that error throwing/catching is much faster with this change, including during performance profiling.

I say this is good to go.

File: src/workerd/io/worker.c++ (hunk 1 above)
Comment (mhart) [reply src/workerd/io/worker.c++:1931]: Performance is still faster in the inspector after this change. Happy to revisit if we want to remove this altogether, but for now it achieves the aim of https://github.com/cloudflare/workerd/issues/5332 so I think it's easier to keep it.
